export const SERVICE_LANGUAGES = [
  // Most Spoken Languages
  'English',
  'Mandarin',
  'Hindi',
  'Spanish',
  'French',
  'Arabic',
  'Bengali',
  'Russian',
  'Portuguese',
  // Additional Widely Spoken Languages
  'German',
  'Japanese',
  'Punjabi',
  'Javanese',
  'Korean',
  'Turkish',
  'Vietnamese',
  'Italian',
  'Urdu',
  'Persian (Farsi)',
  'Swahili',
  // Regional and Cultural Languages
  'Tamil',
  'Telugu',
  'Marathi',
  'Gujarati',
  'Kannada',
  'Malayalam',
  'Thai',
  'Tagalog (Filipino)',
  'Malay',
  'Dutch',
  'Polish',
  'Ukrainian',
  'Czech',
  'Hungarian',
  'Romanian',
  'Greek',
  'Hebrew',
  'Amharic',
  // Indigenous and Niche Languages
  'Hausa',
  'Igbo',
  'Yoruba',
  'Zulu',
  'Xhosa',
  'Maori',
  'Inuktitut',
  'Hawaiian',
  'Samoan',
  'Cherokee',
  // Other Global Languages
  'Swedish',
  'Norwegian',
  'Danish',
  'Finnish',
  'Icelandic',
  'Serbian',
  'Croatian',
  'Bosnian',
  'Slovak',
  'Bulgarian',
  'Albanian',
  'Latvian',
  'Lithuanian',
  'Estonian',
  // Sign Languages
  'American Sign Language (ASL)',
  'British Sign Language (BSL)',
  'French Sign Language (LSF)',
  'International Sign (IS)',
  // Specialized and Rare Languages
  'Latin',
  'Esperanto',
  'Gaelic (Irish)',
  'Scottish Gaelic',
  'Welsh',
  'Basque',
  'Catalan',
  'Luxembourgish',
  'Maltese',
  // Creole and Pidgin Languages
  'Haitian Creole',
  'Jamaican Patois',
  'Tok Pisin',
  // Dialects and Variants
  'Mexican Spanish',
  'Castilian Spanish',
  'Quebec French',
  'Egyptian Arabic',
  'Gulf Arabic',
  'Cantonese',
  'Taiwanese Mandarin',
];

export const SERVICE_TAGS = [
  // Scheduling and Frequency
  'Monday & Friday',
  'Weekly',
  'Bi-Weekly',
  'Monthly',
  'One-Time Session',
  'Daily Support',
  'Quarterly Check-Ins',
  'Weekend Sessions',
  'Morning Availability',
  'Evening Availability',
  'Flexible Scheduling',
  '24/7 Availability',
  // Session Formats
  'Group Sessions',
  'One-on-One Coaching',
  'Workshops',
  'Webinars',
  'On-Demand Content',
  'Live Sessions',
  'Recorded Sessions',
  'Self-Paced Programs',
  'Interactive Activities',
  'Accountability Calls',
  // Audience Types
  'For Beginners',
  'Advanced Level',
  'Teens',
  'Young Adults',
  'Parents',
  'Corporate Teams',
  'Executives',
  'Women Only',
  'Men Only',
  'LGBTQ+ Inclusive',
  'Small Businesses',
  'Entrepreneurs',
  // Session Outcomes
  'Action Plans',
  'Goal Tracking',
  'Problem Solving',
  'Career Guidance',
  'Skill Development',
  'Conflict Resolution',
  'Stress Relief',
  'Empowerment',
  'Habit Building',
  'Increased Productivity',
  // Coaching Tools
  'Journaling Exercises',
  'Guided Meditations',
  'Visualization Techniques',
  'Mind Mapping',
  'Role-Playing',
  'Accountability Tools',
  'Behavioral Assessments',
  'Personality Tests',
  // Communication Methods
  'Zoom Calls',
  'Phone Sessions',
  'In-Person',
  'Email Support',
  'Chat Support',
  'Video Lessons',
  'Hybrid (Online & Offline)',
  'WhatsApp Communication',
  // Special Features
  'Free Consultation',
  'Trial Session',
  'Customizable Packages',
  'Follow-Up Sessions',
  'Access to Resources',
  'Certificates of Completion',
  'Exclusive Community Access',
  'VIP Coaching',
  // Topics Covered
  'Confidence Boost',
  'Career Planning',
  'Stress Management',
  'Leadership Skills',
  'Time Management',
  'Relationship Advice',
  'Financial Literacy',
  'Spiritual Growth',
  'Health and Wellness',
  // Pricing and Payment
  'Pay-As-You-Go',
  'Subscription Model',
  'Bundle Discounts',
  'Sliding Scale Pricing',
  'Scholarship Options',
  'Installment Plans',
  'Refund Policy',
  // Languages and Accessibility
  'English',
  'Spanish',
  'French',
  'Arabic',
  'Hindi',
  'Bilingual Support',
  'Sign Language',
  'Accessible Coaching',
  'Multilingual Programs',
  // Session Duration
  '15-Minute Sessions',
  '30-Minute Sessions',
  '1-Hour Sessions',
  'Full-Day Workshop',
  'Half-Day Workshop',
  'Intensive Bootcamp',
  '3-Month Program',
  '6-Month Program',
  'Yearly Program',
  // Industry-Specific Tags
  'Tech Professionals',
  'Healthcare Workers',
  'Education Sector',
  'Creative Professionals',
  'Finance Industry',
  'Startups',
  'Corporate Leadership',
  // Miscellaneous
  'Goal-Oriented',
  'Results-Driven',
  'Holistic Approach',
  'Transformational',
  'Flexible Commitment',
  'Stress-Free Environment',
];
export const SERVICE_MAIN_TOPICS = [
  // Self Development
  'Self Perspective',
  'Personal Growth',
  'Confidence',
  'Self-Awareness',
  'Mindfulness',
  'Self-Discipline',
  'Emotional Intelligence',
  'Overcoming Self-Doubt',
  'Resilience',
  'Self-Love',
  'Personal Values',
  'Self-Motivation',
  // Career and Professional Growth
  'Career Planning',
  'Leadership Skills',
  'Time Management',
  'Work-Life Balance',
  'Communication Skills',
  'Negotiation Skills',
  'Team Building',
  'Entrepreneurship',
  'Conflict Resolution',
  'Career Transitions',
  'Public Speaking',
  'Personal Branding',
  // Relationships
  'Building Relationships',
  'Conflict Management',
  'Family Dynamics',
  'Parenting Skills',
  'Romantic Relationships',
  'Improving Communication',
  'Empathy and Understanding',
  'Strengthening Bonds',
  'Boundary Setting',
  'Overcoming Relationship Challenges',
  // Health and Wellness
  'Stress Management',
  'Physical Fitness',
  'Mental Health',
  'Workplace Wellness',
  'Healthy Habits',
  'Sleep Optimization',
  'Overcoming Burnout',
  'Nutrition and Dieting',
  'Mind-Body Connection',
  'Relaxation Techniques',
  // Life Transitions
  'Navigating Change',
  'Life Purpose Discovery',
  'Retirement Planning',
  'Starting a New Chapter',
  'Overcoming Setbacks',
  'Building a New Identity',
  'Handling Uncertainty',
  'Adjusting to Parenthood',
  'Relocation Challenges',
  // Spirituality and Fulfillment
  'Spiritual Growth',
  'Meaning and Purpose',
  'Gratitude Practices',
  'Visualization Techniques',
  'Finding Inner Peace',
  'Faith and Belief Systems',
  'Living Authentically',
  // Financial Growth
  'Financial Literacy',
  'Budgeting and Saving',
  'Wealth Mindset',
  'Investing Basics',
  'Debt Management',
  'Financial Independence',
  'Entrepreneurial Finances',
  // Creativity and Innovation
  'Unlocking Creativity',
  'Problem-Solving Skills',
  'Design Thinking',
  'Creative Expression',
  'Innovation Strategies',
  'Brainstorming Techniques',
  // Coaching-Specific Topics
  'Effective Goal Setting',
  'Accountability Strategies',
  'Coaching Tools and Techniques',
  'Motivational Strategies',
  'Listening Skills',
  'Providing Feedback',
  'Facilitating Growth',
  'Coaching for Performance',
  // Social Impact and Legacy
  'Community Engagement',
  'Making a Difference',
  'Philanthropy',
  'Sustainability Practices',
  'Creating Your Legacy',
  'Activism and Advocacy',
  // Habits and Productivity
  'Building Habits',
  'Breaking Bad Habits',
  'Daily Routines',
  'Productivity Hacks',
  'Focus and Attention',
  'Overcoming Procrastination',
  'Maximizing Energy',
  // Emotional Wellbeing
  'Overcoming Fear',
  'Managing Anxiety',
  'Handling Criticism',
  'Letting Go of Guilt',
  'Finding Joy',
  'Anger Management',
  'Forgiveness Practices',
  'Healing from Trauma',
  'Dealing with Grief',
  // Specialized Topics
  'Diversity and Inclusion',
  'Cultural Awareness',
  'Navigating Identity',
  'Women Empowerment',
  'Men’s Issues',
  'LGBTQ+ Coaching',
  'Neurodivergence Coaching',
  'Coaching for Teens',
  'Coaching for Executives',
  // Business Growth
  'Scaling a Business',
  'Marketing Strategies',
  'Social Media Presence',
  'Sales Techniques',
  'Customer Retention',
  'Online Business Models',
  'Building a Team',
  'Brand Loyalty',
  'Digital Transformation',
  // Life Skills
  'Decision-Making Skills',
  'Critical Thinking',
  'Adaptability',
  'Problem Solving',
  'Learning How to Learn',
  'Taking Initiative',
  'Overcoming Limiting Beliefs',
  // Miscellaneous
  'Adventure and Exploration',
  'Hobbies and Interests',
  'Living Sustainably',
  'Minimalism',
  'Decluttering',
  'Bucket List Goals',
  'Rediscovering Passions',
];

export const SERVICE_CATEGORIES = [
  // Business and Career
  'Business Coaching',
  'Executive Coaching',
  'Career Coaching',
  'Leadership Coaching',
  'Team Coaching',
  'Entrepreneurship Coaching',
  'Sales Coaching',
  'Start-Up Coaching',
  'Small Business Coaching',
  // Life and Personal Growth
  'Life Coaching',
  'Personal Growth Coaching',
  'Confidence Coaching',
  'Transition Coaching',
  'Resilience Coaching',
  'Mindfulness Coaching',
  'Self-Awareness Coaching',
  'Happiness Coaching',
  'Goal Setting Coaching',
  // Health and Wellness
  'Health Coaching',
  'Wellness Coaching',
  'Stress Management Coaching',
  'Emotional Intelligence Coaching',
  'Nutrition Coaching',
  'Fitness Coaching',
  'Sleep Coaching',
  'Mental Health Coaching',
  'Holistic Wellness Coaching',
  // Relationships and Family
  'Relationship Coaching',
  'Parenting Coaching',
  'Family Coaching',
  'Romantic Relationship Coaching',
  'Boundary Setting Coaching',
  'Conflict Resolution Coaching',
  // Financial and Performance
  'Financial Coaching',
  'Performance Coaching',
  'Productivity Coaching',
  'Time Management Coaching',
  'Wealth Mindset Coaching',
  // Creativity and Fulfillment
  'Creativity Coaching',
  'Artistic Coaching',
  'Innovation Coaching',
  'Passion and Purpose Coaching',
  // Spirituality and Inner Work
  'Spiritual Coaching',
  'Meditation Coaching',
  'Inner Peace Coaching',
  'Values Alignment Coaching',
  'Energy Healing Coaching',
  // Academic and Skills Development
  'Academic Coaching',
  'Study Skills Coaching',
  'Test Preparation Coaching',
  'Learning Skills Coaching',
  'Language Coaching',
  // Psychology and Therapy
  'Psychology',
  'Counseling',
  'Therapy',
  'Cognitive Behavioral Therapy (CBT)',
  'Positive Psychology',
  'Organizational Psychology',
  'Sports Psychology',
  'Clinical Psychology',
  'Educational Psychology',
  'Industrial-Organizational Psychology',
  'Developmental Psychology',
  'Forensic Psychology',
  'Neuropsychology',
  'Social Psychology',
  'Health Psychology',
  // Therapeutic Modalities
  'Psychotherapy',
  'Behavioral Therapy',
  'Humanistic Therapy',
  'Integrative Therapy',
  'Mind-Body Therapy',
  'Psychodynamic Therapy',
  'Coaching Psychology',
  // Specialized Coaching
  'Transition Coaching',
  'Diversity and Inclusion Coaching',
  'Crisis Coaching',
  'Retirement Coaching',
  'Executive Presence Coaching',
  'Public Speaking Coaching',
  'Adaptability Coaching',
  'Special Needs Coaching',
  // Industry-Specific Coaching
  'Tech Industry Coaching',
  'Creative Industry Coaching',
  'Education Sector Coaching',
  'Healthcare Coaching',
  'Real Estate Coaching',
  'Legal Industry Coaching',
  'Hospitality Coaching',
];

export const SERVICE_TIME_OPTIONS = [
  { value: '60', label: '1 Hour' },
  { value: '90', label: '1:30 Hours' },
  { value: '120', label: '2 Hour' },
  { value: '180', label: '2:30 Hours' },
  { value: 'Custom', label: 'Custom' },
];

export const SERVICE_DAYS_AVAILABILITY = [
  { value: 'monday', label: 'Monday' },
  { value: 'tuesday', label: 'Tuesday' },
  { value: 'wednesday', label: 'Wednesday' },
  { value: 'thursday', label: 'Thursday' },
  { value: 'friday', label: 'Friday' },
  { value: 'saturday', label: 'Saturday' },
  { value: 'sunday', label: 'Sunday' },
];

export const SERVICE_PERIODICITY = [
  { value: 'one-time', label: 'One-Time' },
  { value: 'daily', label: 'Daily' },
  { value: 'weekly', label: 'One per Week-(Weekly)' },
];
